### ISSUE TITLE
Is there free to join?

### ISSUE THREAD

**Issue by qianxliu** [LambdaInnovation/mu#1]
I'm looking forward to organization about game dev. Is there any possibility that I could join?
这个组织对于加入成员free吗？在找游戏开发相关的组织……

**Comment by qianxliu** [comment]
@mkpoli @WeAthFoLD @NolifeM @acaly @Lyt99 @WeAthFoLD @KSkun
可以自由加入吗？GitHub似乎没有很多关于游戏开发的组织

**Comment by WeAthFoLD** [comment]
Hi, LI是我和一些朋友创建的爱好小组，目前讨论的东西也很杂，不太算是个游戏开发小组，所以可能不太满足你的预期，sorry :-P

**Comment by qianxliu** [comment]
没关系的，各位继续加油吧

其实现在我也意识到游戏实质上是个蛮严肃的事情……合作真的也比较麻烦
除非做那些不严肃的作品
所以说GitHub上也没有多少游戏开发组
