### ISSUE TITLE
Hi.

### ISSUE THREAD

**Issue by KamiSami** [LambdaInnovation/mu#2]
In honesty before i begin, I hate to be the one barging in first to get the attention needed, but the thing I want to talk about... It has come to my attention for awhile now that your mod "AcademyCraft" has been possibly abandoned(?, confirm me if not), if this is the case, would you be kind enough to at very least let your discord community to be let known about of this? Some of us are just waiting in the dark with nothing given in, don't be doing same what Emoniph did to his mods who just left without saying anything at all. So please, if you plan to continue the mod or not, doesn't matter which, let at least your community know in Discord what is up. Thanks for your time reading this, feel free to close this issue after reading and hopefully understanding.

**Comment by WeAthFoLD** [comment]
Hi. I am currently working full time as game programmer in the past few years. I have tried maintaining and updating AcademyCraft in 2018 and 2019 (with the result of upgrading it to MC1.12), but it proved that my personal energy is simply not enough for such a big project (either developing or managing it). With the additional fact that nobody else is interested enough in maintaing the project in the long run, I am sorry to say, yes that the project is currently in a discontinued state.

My personal interest also **shifted greatly** in these years, from MC modding to much bigger goals such as game design, general game developement etc. That's a pretty big chunk of meat to take, and that takes a great amount of effort and concerntration. Therefore I have no interest in coming back to MC modding in any recent time.

AC has been both a great **achievement** and **mental burnout** for me, and I always have a mix of love and hate in developing it. But for now, I have to move on. And I'm truly sorry for the unforetold leave.

That being said, I'm more than willing to provide any resource if anyone wants to continue developing the mod.

There is in fact one little update for AC but I didn't take time (yet) to release it, but it contains mostly bugfix and nothing to serious. I will find some time release it soon.
